<?php
// project-root/private/registry/subjects.php

// Default 19 subjects (safe to overwrite in updates). Used if subjects.php is missing.
return [
  1  => ['id'=>1,  'name'=>'History',      'name_id'=>'history',      'slug'=>'history',      'nav_order'=>1,  'meta_description'=>'Pages related to history.',       'meta_keywords'=>'history, past, heritage, records',            'icon'=>'lib/images/logo/history.svg'],
  2  => ['id'=>2,  'name'=>'Slavery',      'name_id'=>'slavery',      'slug'=>'slavery',      'nav_order'=>2,  'meta_description'=>'Pages related to slavery.',       'meta_keywords'=>'slavery, trade, bondage, history',            'icon'=>'lib/images/logo/slavery.svg'],
  3  => ['id'=>3,  'name'=>'People',       'name_id'=>'people',       'slug'=>'people',       'nav_order'=>3,  'meta_description'=>'Pages related to people.',        'meta_keywords'=>'people, community, individuals',              'icon'=>'lib/images/logo/people.svg'],
  4  => ['id'=>4,  'name'=>'Persons',      'name_id'=>'persons',      'slug'=>'persons',      'nav_order'=>4,  'meta_description'=>'Pages related to persons.',       'meta_keywords'=>'persons, individuals, biographies',           'icon'=>'lib/images/logo/persons.svg'],
  5  => ['id'=>5,  'name'=>'Culture',      'name_id'=>'culture',      'slug'=>'culture',      'nav_order'=>5,  'meta_description'=>'Pages related to culture.',       'meta_keywords'=>'culture, lifestyle, arts, heritage',          'icon'=>'lib/images/logo/culture.svg'],
  6  => ['id'=>6,  'name'=>'Religion',     'name_id'=>'religion',     'slug'=>'religion',     'nav_order'=>6,  'meta_description'=>'Pages related to religion.',      'meta_keywords'=>'religion, faith, worship, belief',            'icon'=>'lib/images/logo/religion.svg'],
  7  => ['id'=>7,  'name'=>'Spirituality', 'name_id'=>'spirituality', 'slug'=>'spirituality', 'nav_order'=>7,  'meta_description'=>'Pages related to spirituality.',  'meta_keywords'=>'spirituality, meditation, faith, soul',       'icon'=>'lib/images/logo/spirituality.svg'],
  8  => ['id'=>8,  'name'=>'Tradition',    'name_id'=>'tradition',    'slug'=>'tradition',    'nav_order'=>8,  'meta_description'=>'Pages related to tradition.',     'meta_keywords'=>'tradition, customs, practices, heritage',     'icon'=>'lib/images/logo/tradition.svg'],
  9  => ['id'=>9,  'name'=>'Language 1',   'name_id'=>'language1',    'slug'=>'language1',    'nav_order'=>9,  'meta_description'=>'Pages related to first language.', 'meta_keywords'=>'language, communication, dialect',            'icon'=>'lib/images/logo/language1.svg'],
  10 => ['id'=>10, 'name'=>'Language 2',   'name_id'=>'language2',    'slug'=>'language2',    'nav_order'=>10, 'meta_description'=>'Pages related to second language.','meta_keywords'=>'language, communication, dialect',           'icon'=>'lib/images/logo/language2.svg'],
  11 => ['id'=>11, 'name'=>'Struggles',    'name_id'=>'struggles',    'slug'=>'struggles',    'nav_order'=>11, 'meta_description'=>'Pages related to struggles.',     'meta_keywords'=>'struggles, resistance, survival',             'icon'=>'lib/images/logo/struggles.svg'],
  12 => ['id'=>12, 'name'=>'Biafra',       'name_id'=>'biafra',       'slug'=>'biafra',       'nav_order'=>12, 'meta_description'=>'Pages related to Biafra.',        'meta_keywords'=>'biafra, war, independence, nigeria',          'icon'=>'lib/images/logo/biafra.svg'],
  13 => ['id'=>13, 'name'=>'Nigeria',      'name_id'=>'nigeria',      'slug'=>'nigeria',      'nav_order'=>13, 'meta_description'=>'Pages related to Nigeria.',       'meta_keywords'=>'nigeria, nation, politics, history',          'icon'=>'lib/images/logo/nigeria.svg'],
  14 => ['id'=>14, 'name'=>'IPOB',         'name_id'=>'ipob',         'slug'=>'ipob',         'nav_order'=>14, 'meta_description'=>'Pages related to IPOB.',          'meta_keywords'=>'ipob, biafra, movement, nigeria',             'icon'=>'lib/images/logo/ipob.svg'],
  15 => ['id'=>15, 'name'=>'Africa',       'name_id'=>'africa',       'slug'=>'africa',       'nav_order'=>15, 'meta_description'=>'Pages related to Africa.',        'meta_keywords'=>'africa, continent, heritage, nations',        'icon'=>'lib/images/logo/africa.svg'],
  16 => ['id'=>16, 'name'=>'UK',           'name_id'=>'uk',           'slug'=>'uk',           'nav_order'=>16, 'meta_description'=>'Pages related to the UK.',        'meta_keywords'=>'uk, britain, england, london',                'icon'=>'lib/images/logo/uk.svg'],
  17 => ['id'=>17, 'name'=>'Europe',       'name_id'=>'europe',       'slug'=>'europe',       'nav_order'=>17, 'meta_description'=>'Pages related to Europe.',        'meta_keywords'=>'europe, continent, nations, history',         'icon'=>'lib/images/logo/europe.svg'],
  18 => ['id'=>18, 'name'=>'Arabs',        'name_id'=>'arabs',        'slug'=>'arabs',        'nav_order'=>18, 'meta_description'=>'Pages related to Arabs.',         'meta_keywords'=>'arabs, middle east, culture, history',        'icon'=>'lib/images/logo/arabs.svg'],
  19 => ['id'=>19, 'name'=>'About',        'name_id'=>'about',        'slug'=>'about',        'nav_order'=>19, 'meta_description'=>'About this website.',            'meta_keywords'=>'about, information, project, overview',       'icon'=>'lib/images/logo/about.svg'],
];
