name: Mirror main to backup

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push branches to backup
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add backup "https://${{ secrets.BACKUP_TOKEN }}@github.com/${{ secrets.BACKUP_REPO }}.git"
          git push --all backup --force
          git push --tags backup --force
